---
apiVersion: v1
kind: Service
metadata:
  name: tbbpython
  namespace: dev
spec:
  selector:
    app: tbbpython
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    nodePort: 31100
