apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tbbpython
  name: tbbpython
  namespace: dev
spec:
  replicas: 1      
  selector:
    matchLabels:
      app: tbbpython    
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tbbpython
    spec:
      containers:
      - name: tbbpython
        image: foti06/tbb-bitirme:tbbpython
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: MYSQL_USERNAME
          value: "root"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: MYSQL_INSTANCE_NAME
          value: "sehirler"
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: "mydb" 
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"    

         
                  
