

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: dev
type: Opaque
data:
  password: YWRtaW4xMjMK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        # Use secret in real usage
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim


