apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
  namespace: dev
  labels:
    app: mydb
spec:
  replicas: 1      
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels: 
        app: mydb      
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password 
        args: ["--default-authentication-plugin=mysql_native_password"]      
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config    


