apiVersion: v1
kind: Service
metadata:
  name: mydb
  namespace: dev
spec:
  selector:
    app: mydb
  ports:
    - port: 3306
      protocol: TCP
      nodePort: 30110
      name: mysql
  type: NodePort

